### ISSUE TITLE
Add mlbox-example SciML benchmark

### ISSUE THREAD

**Issue by sub-mod** [mlcommons/mlcube#112]
Assigned to vibhatha
https://github.com/mlperf/box_examples

**Comment by petermattson** [comment]
Hi Subin et al,
Can you please clarify what this issue is supposed to be about?
Best,
Peter

**Comment by sub-mod** [comment]
@petermattson This issue was assigned to a grad student who is creating mlbox for a SciML workload.
The example would be pushed to mlperf/box_examples repo.

**Comment by vibhatha** [comment]
@sub-mod I added a draft PR to https://github.com/mlperf/box_examples/pull/3
