### ISSUE TITLE
Mlbox demo run

### ISSUE THREAD

**Issue by sub-mod** [mlcommons/mlcube#113]

**Comment by petermattson** [comment]
Hi Subin et al,
Can you please clarify what this issue is supposed to be about?
Best,
Peter

**Comment by sub-mod** [comment]
@petermattson This issues was about set of steps which would be used to run mlbox examples.
These demo runs would be published publicly so that users can try out the steps to use mlbox and the steps would also exhibit all usecase for using mlbox.
