### ISSUE TITLE
Fix up examples to work with current runner

### ISSUE THREAD

**Issue by bitfort** [mlcommons/mlcube#186]
The current MLCube runner has changed since our examples were created; take a look at these examples and if they don't run, see if you can make the changes to have them. 
https://github.com/mlcommons/mlcube_examples/tree/master/hello_world
https://github.com/mlcommons/mlcube_examples/tree/master/matmul
https://github.com/mlcommons/mlcube_examples/tree/master/mnist

**Comment by bitfort** [comment]
Also - update any documents that seem out of date!

**Comment by davidjurado** [comment]
Hello Victor,

For the three examples, the only issue I encounter was related to the SSH runner. I'm not sure what is causing the error, here is a [screenshot](https://i.imgur.com/Tg5Mfcz.png) of an output that I got in the Hello World example.

I used my Ubuntu machine as the host **mlcube-remote** and on the screenshot, you can see I was able to connect to it from my Mac, but the command for configuring didn't work: ```mlcube_ssh configure --mlcube=. --platform=platforms/ssh.yaml```

The Docker and Singularity runners worked as expected, here are some screenshots of the outputs for the three examples: [hello_word](https://i.imgur.com/Hs4aLvl.png), [matmul](https://i.imgur.com/V49UGxG.png), [mnist](https://i.imgur.com/2VSl8sM.png).

**Comment by bitfort** [comment]
All of them work?! That's awesome. I did not expect them to all still be functional :)

Are there any updates to the readme that would help people run them? If not, feel free to close the issue.

**Comment by davidjurado** [comment]
The readme files are well explained, I couldn't find anything to add or fix, the only part that didn't work was the SSH runner, I'm trying to figure out what is the problem there.

**Comment by bitfort** [comment]
Sounds great! Thanks!

Feel free to make any updates you like, and the look at:
#188 and #187
