### ISSUE TITLE
MLCube Config 2.0 

### ISSUE THREAD

**Issue by bitfort** [mlcommons/mlcube#189]
Hi All, 

We need to start on our config 2.0 push to make MLCubes easier and simpler for everyone :)

This looks like:
(1) Reducing the number of config files we use
(2) Reducing the data needed in config files

Let's 3 talk about what this looks like and push forward on it. 

@davidjurado I think the first step is getting you set up to work on the MLCube package, e.g. https://github.com/mlcommons/mlcube/tree/master/mlcube/mlcube

Please take a look at the code :)

**Comment by sergey-serebryakov** [comment]
Config 2.0 was merged into master.
