### ISSUE TITLE
Web Site Broken

### ISSUE THREAD

**Issue by laszewsk** [mlcommons/mlcube#190]
The links 

- https://mlcommons.github.io/mlcube/getting-started/mnist/
- https://mlcommons.github.io/mlcube/tutorials/create-mlcube/

are broken

**Comment by sergey-serebryakov** [comment]
Hi!
Please, try these links:
* https://mlcommons.github.io/mlcube/getting-started/mnist.html
* https://mlcommons.github.io/mlcube/tutorials/create-mlcube.html

**Comment by danielsnider** [comment]
+1

These links are broken on this website: https://mlcommons.org/en/mlcube/

**Comment by TheKanter** [comment]
Hi Folks, I believe this is fixed now.

Can someone (e.g., @danielsnider @sergey-serebryakov @laszewsk ) test to confirm and then close this issue?

**Comment by bitfort** [comment]
Links fixed in website.
