### ISSUE TITLE
Custom workspace directory

### ISSUE THREAD

**Issue by tanertopal** [mlcommons/mlcube#194]
Currently the workspace directory is shared by multiple invocations of `mlcube_docker` which makes some use-cases harder to implement. It would be great to have a command argument which allows setting the workspace directory explicitly.

As an example:

```bash
mlcube_docker run \
  --mlcube=. \
  --platform=platforms/docker.yaml \
  --task=run/download.yamlmlcube_docker configure \
  --workspace=/opt/custom_workspace
```

ideally it would be possible to provide a relative path to cwd and an absolute path.

Currently the only solution seems to be (please correct me if there is an alternative) to copy/paste the whole mlcube including source code and run and task specs into a extra directory.

**Comment by bitfort** [comment]
Great runner feature to add. Let's add --workspace=/opt/custom_workspace; perhaps in the future this can be set in the runner config, too.

**Comment by sergey-serebryakov** [comment]
I am closing it, if there's a bug or additional functionality is required, please, feel free to reopen it.
