### ISSUE TITLE
Upgrade click to `>=8.0.0,<9.0.0`

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/mlcube#287]
Both medperf and MLCube depend on click for their CLIs. Medperf is encountering a click issue when running on Windows, as explained by issue https://github.com/tiangolo/typer/issues/427

The proposed solution is to install `click>=8.0.0,<9.0.0`, but mlcube depends on `click==7.1.2`, causing a `ResolutionImpossible` error.

Would it be possible to upgrade to the requested versions? Of course, assuming this doesn't break anything on your side.

**Comment by sergey-serebryakov** [comment]
Working on this today, should be possible.

**Comment by sergey-serebryakov** [comment]
I updated the `click` version and MLCube code. MLCube core library has no conflicts. Almost all MLCube runner have no conflicts as well except  one - KubeFlow runner. It depends on `kfp` library that needs click 7.1.2. Need advice / possible solutions how to fix this.

**Comment by aristizabal95** [comment]
Hmm it's not as clean as expected. I'll see if I can bypass Typer's error another way for Windows. Thanks for the support! Let me know if anything changes on your side

**Comment by aristizabal95** [comment]
Downgrading `typer` to `<0.5.0` fixed my issue without requiring changes to other dependencies. This issue can be closed

**Comment by sergey-serebryakov** [comment]
@aristizabal95 Turns out there's a super simple solution - upgrading `kfp` version to `1.8.18`. I have not tested the Kubeflow runner though (it's not that important at this point in time anyway). So, we can actually upgrade the click version.

**Comment by sergey-serebryakov** [comment]
Implemented in #297.

**Comment by sergey-serebryakov** [comment]
Done.
