### ISSUE TITLE
[Medperf] update cookiecutter for dependency resolution

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/mlcube#300]
Medperf needs to update some dependencies due to security vulnerabilities. Specifically, we need to merge the following PR: https://github.com/mlcommons/medperf/pull/386. This causes a dependency issue, because that PR requires cookiecutter v2.1.1, but MLCube uses an older version of cookiecutter. There's already a PR for this update #252 , would it be possible to merge for future releases?

**Comment by sergey-serebryakov** [comment]
Done!
